### PR TITLE
NBC-4

### PR DESCRIPTION
**Pull request by simonmarklar**
- Add unique file name generation
- Zip files into the generated name

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
It occurs to me that our blinkmobile/aws-s3 library is (so far) designed for synchronising directories with multiple files to S3 Buckets with objects that we care about, and this use case is really just uploading a single file (ignoring remote contents). Maybe our library isn't necessary here? Or maybe single-file use case should be supported by our extracted library?

Also, for projects like this that are not libraries, I recommend that we lock the version of "dependencies" to give us some measure of control (remove the "^"s in package.json). I feel "devDependencies" are more convenient to leave as version ranges, at least until that bites us, too. :)

**Comment by jokeyrhyme** [comment]
By the way, mockery looks like it was accidentally put in "dependencies", when you probably meant for it to be in "depDependencies".

**Comment by jokeyrhyme** [comment]
LGTM :+1:

**Comment by simonmarklar** [comment]
Hmm I thought the s3 uploader could handle single files via the filepaths parameter (eg `glob([ "full/path/to/file.zip"])` ) ??

I think it would be worth putting single file upload into the uploader if it doesn't have it.

**Comment by jokeyrhyme** [comment]
> Hmm I thought the s3 uploader could handle single files via the filepaths parameter (eg `glob([ "full/path/to/file.zip"])` ) ??

True. But it'll also automatically retrieve the hashes of every single Object in the S3 Bucket, then compare the hash of that single file to its remote hash (if any).

There's loads of stuff happening there that isn't necessary for this use case.

**Pull request merged**
